export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_FIELDS_DESIGN = 'UPDATE_FIELDS_DESIGN';
export const UPDATE_WALLS_DESIGN = 'UPDATE_WALLS_DESIGN';
export const UPDATE_MENU_STATE = 'UPDATE_MENU_STATE';
export const UPDATE_ITEM_ACTION = 'UPDATE_ITEM_ACTION';
export const UPDATE_BORDER_STATE = 'UPDATE_BORDER_STATE';
