// BALL
const USE_DARK_RED_BALL = 'USE_DARK_RED_BALL';
const USE_ICE_BALL = 'USE_ICE_BALL';
const USE_NEON_BLUE_BALL = 'USE_NEON_BLUE_BALL';

// DOOR
const USE_BLACK_DOOR = 'USE_BLACK_DOOR';
const USE_GOLD_DOOR = 'USE_GOLD_DOOR';
const USE_ICE_DOOR = 'USE_ICE_DOOR';

// ITEMS
const USE_GOLD = 'USE_GOLD';
const USE_SILVER = 'USE_SILVER';
const USE_DIAMOND = 'USE_DIAMOND';
const USE_EMERALD = 'USE_EMERALD';
const USE_SAPPHIRE = 'USE_SAPPHIRE';
const USE_RUBY = 'USE_RUBY';

//ENEMY
const USE_NEON_RED_ENEMY = 'USE_NEON_RED_ENEMY';
const USE_NEON_GREEN_ENEMY = 'USE_NEON_GREEN_ENEMY';
const USE_NEON_BLUE_ENEMY = 'USE_NEON_BLUE_ENEMY';

// ERASER

const USE_ERASER = 'USE_ERASER';

export {
  //BALL
  USE_DARK_RED_BALL,
  USE_ICE_BALL,
  USE_NEON_BLUE_BALL,
  // DOOR
  USE_BLACK_DOOR,
  USE_GOLD_DOOR,
  USE_ICE_DOOR,
  // ITEMS
  USE_GOLD,
  USE_SILVER,
  USE_DIAMOND,
  USE_EMERALD,
  USE_SAPPHIRE,
  USE_RUBY,
  // ENEMY
  USE_NEON_RED_ENEMY,
  USE_NEON_GREEN_ENEMY,
  USE_NEON_BLUE_ENEMY,
  //ERASER
  USE_ERASER,
};

export const NUMBER_OF_ROWS = 10;
export const NUMBER_OF_COLUMNS = 9;
export const BOARD_WIDTH = 299;
export const BOARD_HEIGHT = 430;
export const SENSITIVITY = 0.0;
export const FIELD_WIDTH = BOARD_WIDTH / NUMBER_OF_COLUMNS;
export const FIELD_HEIGHT = BOARD_HEIGHT / NUMBER_OF_ROWS;

export const VERTICAL_BRICK_S_HEIGHT = FIELD_HEIGHT * 0.5;
export const VERTICAL_BRICK_M_HEIGHT = FIELD_HEIGHT * (2 / 3);
export const VERTICAL_BRICK_WIDTH = 0.5 * FIELD_WIDTH;

export const HORIZONTAL_BRICK_WIDTH = FIELD_WIDTH;
export const HORIZONTAL_BRICK_HEIGHT = FIELD_HEIGHT * (1 / 3);
export const BALL_SIZE = HORIZONTAL_BRICK_HEIGHT / 2; //10;
